name: release

on:
  push:
    # run only against tags
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: git fetch --force --tags
      - run: go generate ./...
      - uses: actions/setup-go@v3
        with:
          go-version: '1.22'
          cache: true
      - uses: goreleaser/goreleaser-action@v4
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
          workdir: ./cmd/izu/
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
