name: test

on: 
  push:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v3
        with:
          go-version: '1.22'
          cache: true
      - name: Run test
        id: run-test
        run: |
          go mod download
          go generate ./...
          go test ./...

